
services:
  ganache:
    image: trufflesuite/ganache:v7.9.1
    ports:
      - "8545:8545"
    command:
      - --accounts=10
      - --defaultBalanceEther=1000
      - --mnemonic="candy maple cake sugar pudding cream honey rich smooth crumble sweet treat"
      - --chain.networkId=1337
      - --chain.chainId=1337
    healthcheck:
      test: ["CMD-SHELL", "timeout 1 bash -c '</dev/tcp/localhost/8545' || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s
  deployer:
    build:
      context: .
      dockerfile: Dockerfile.blockchain
    environment:
      - BESU_RPC_URL=http://ganache:8545
      - PRIVATE_KEY=0x4f3edf983ac636a65a842ce7c78d9aa706d3b113b37b1c6f0e2e5f4a47f6edc3 # Ganache default
    depends_on:
      ganache:
        condition: service_healthy
